### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0

### ISSUE THREAD

**Issue by LaoTsing** [r2dbc/r2dbc-pool#19]
<dependency>
           <groupId>io.r2dbc</groupId>
           <artifactId>r2dbc-postgresql</artifactId>
           <version>0.8.0.BUILD-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>io.r2dbc</groupId>
            <artifactId>r2dbc-pool</artifactId>
            <version>0.8.0.BUILD-SNAPSHOT</version>
        </dependency>

```
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at reactor.core.publisher.FluxOnAssembly$OnAssemblyException.toTuple(FluxOnAssembly.java:220) ~[reactor-core-3.3.0.M1.jar:3.3.0.M1]
	at reactor.core.publisher.FluxOnAssembly$OnAssemblyException.<init>(FluxOnAssembly.java:206) ~[reactor-core-3.3.0.M1.jar:3.3.0.M1]
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.fail(FluxOnAssembly.java:410) ~[reactor-core-3.3.0.M1.jar:3.3.0.M1]
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onError(FluxOnAssembly.java:354) ~[reactor-core-3.3.0.M1.jar:3.3.0.M1]
	at reactor.core.publisher.Operators.error(Operators.java:182) ~[reactor-core-3.3.0.M1.jar:3.3.0.M1]
	at reactor.core.publisher.FluxError.subscribe(FluxError.java:43) ~[reactor-core-3.3.0.M1.jar:3.3.0.M1]
	at reactor.core.publisher.FluxOnAssembly.subscribe(FluxOnAssembly.java:106) ~[reactor-core-3.3.0.M1.jar:3.3.0.M1]
	at reactor.core.publisher.FluxCallableOnAssembly.subscribe(FluxCallableOnAssembly.java:51) ~[reactor-core-3.3.0.M1.jar:3.3.0.M1]
	at reactor.core.publisher.Flux.subscribe(Flux.java:7800) ~[reactor-core-3.3.0.M1.jar:3.3.0.M1]
	at reactor.core.publisher.FluxUsingWhen$ResourceSubscriber.onNext(FluxUsingWhen.java:201) ~[reactor-core-3.3.0.M1.jar:3.3.0.M1]
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:349) ~[reactor-core-3.3.0.M1.jar:3.3.0.M1]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121) ~[reactor-core-3.3.0.M1.jar:3.3.0.M1]
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:349) ~[reactor-core-3.3.0.M1.jar:3.3.0.M1]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121) ~[reactor-core-3.3.0.M1.jar:3.3.0.M1]
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:349) ~[reactor-core-3.3.0.M1.jar:3.3.0.M1]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73) ~[reactor-core-3.3.0.M1.jar:3.3.0.M1]
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:349) ~[reactor-core-3.3.0.M1.jar:3.3.0.M1]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73) ~[reactor-core-3.3.0.M1.jar:3.3.0.M1]
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:349) ~[reactor-core-3.3.0.M1.jar:3.3.0.M1]
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:67) ~[reactor-core-3.3.0.M1.jar:3.3.0.M1]
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:349) ~[reactor-core-3.3.0.M1.jar:3.3.0.M1]
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:349) ~[reactor-core-3.3.0.M1.jar:3.3.0.M1]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121) ~[reactor-core-3.3.0.M1.jar:3.3.0.M1]
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:349) ~[reactor-core-3.3.0.M1.jar:3.3.0.M1]
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:349) ~[reactor-core-3.3.0.M1.jar:3.3.0.M1]
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:204) ~[reactor-core-3.3.0.M1.jar:3.3.0.M1]
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:349) ~[reactor-core-3.3.0.M1.jar:3.3.0.M1]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121) ~[reactor-core-3.3.0.M1.jar:3.3.0.M1]
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:349) ~[reactor-core-3.3.0.M1.jar:3.3.0.M1]
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:192) ~[reactor-core-3.3.0.M1.jar:3.3.0.M1]
	at reactor.pool.AbstractPool$Borrower.deliver(AbstractPool.java:341) ~[reactor-pool-0.0.1.BUILD-20190610.214858-38.jar:0.0.1.BUILD-SNAPSHOT]
	at reactor.pool.SimplePool.lambda$drainLoop$6(SimplePool.java:204) ~[reactor-pool-0.0.1.BUILD-20190610.214858-38.jar:0.0.1.BUILD-SNAPSHOT]
	at reactor.core.scheduler.ImmediateScheduler.schedule(ImmediateScheduler.java:47) ~[reactor-core-3.3.0.M1.jar:3.3.0.M1]
	at reactor.pool.SimplePool.drainLoop(SimplePool.java:204) ~[reactor-pool-0.0.1.BUILD-20190610.214858-38.jar:0.0.1.BUILD-SNAPSHOT]
	at reactor.pool.SimplePool.drain(SimplePool.java:145) ~[reactor-pool-0.0.1.BUILD-20190610.214858-38.jar:0.0.1.BUILD-SNAPSHOT]
	at reactor.pool.SimplePool.doAcquire(SimplePool.java:113) ~[reactor-pool-0.0.1.BUILD-20190610.214858-38.jar:0.0.1.BUILD-SNAPSHOT]
	at reactor.pool.AbstractPool$Borrower.request(AbstractPool.java:305) ~[reactor-pool-0.0.1.BUILD-20190610.214858-38.jar:0.0.1.BUILD-SNAPSHOT]
```

**Comment by LaoTsing** [comment]
Working after downgrade r2dbc-postgres to 1.0.0.M7 version!

**Comment by bsideup** [comment]
hi @LaoTsing,

Does it also fail if you use `reactor-core` version `3.3.0.M2`? Aka `Dysprosium M2`?

**Comment by LaoTsing** [comment]
hello! may be, my cloud is Hoxton.BUILD-SNAPSHOT and Spring Boot 2.2.0.M3

**Comment by mp911de** [comment]
Closing this ticket as this is (was) a Project Reactor-related issue.
