### ISSUE TITLE
`Wrapped` in `ConnectionPool` unwrapping doesn't guard against implementations returning `this`

### ISSUE THREAD

**Issue by mp911de** [r2dbc/r2dbc-pool#220]
This is a regression introduced by #217

```
java.lang.ClassCastException: class io.r2dbc.postgresql.PostgresqlConnection cannot be cast to class reactor.core.scheduler.Scheduler (io.r2dbc.postgresql.PostgresqlConnection and reactor.core.scheduler.Scheduler are in unnamed module of loader 'app')
	at io.r2dbc.pool.ConnectionPool.lambda$null$4(ConnectionPool.java:118) ~[r2dbc-pool-1.0.2.RELEASE.jar:1.0.2.RELEASE]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:132) ~[reactor-core-3.6.12.jar:3.6.12]
	... 208 common frames omitted
```

**Comment by bcalmac** [comment]
This isssue was reported in November 2024, we are now in June 2025 and it currently breaks all spring-boot applications using R2DBC. When is 1.0.3.RELEASE due?
