### ISSUE TITLE
Using R2DBC pool in a Spring refreshable context leads to IllegalStateException

### ISSUE THREAD

**Issue by cambierr** [r2dbc/r2dbc-pool#31]
Hi all,

I'm using r2dbc pool as part of a Spring WebFlux project using Spring Cloud hot-refresh capabilities based on consul watches.

In this context, my R2DBC PoolableConnection can get re-created with different settings which leads to a new ConnectionPool (SimpleFifoPool in my case) to block in SimplePool: 

```java
SimplePool(DefaultPoolConfig<POOLABLE> poolConfig) {
    // ...
    POOLABLE poolable = Objects.requireNonNull(poolConfig.allocator.block(), "allocator returned null in constructor");
    // ...
}
```
Since this is executed in a reactive context, this lead to: 
```
Caused by: java.lang.IllegalStateException: block()/blockFirst()/blockLast() are blocking, which is not supported in thread reactor-http-epoll-4
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:77) ~[reactor-core-3.2.6.RELEASE.jar!/:3.2.6.RELEASE]
	at reactor.core.publisher.Mono.block(Mono.java:1494) ~[reactor-core-3.2.6.RELEASE.jar!/:3.2.6.RELEASE]
	at reactor.pool.SimplePool.<init>(SimplePool.java:72) ~[reactor-pool-0.0.1.M1.jar!/:0.0.1.M1]
	at reactor.pool.SimpleFifoPool.<init>(SimpleFifoPool.java:41) ~[reactor-pool-0.0.1.M1.jar!/:0.0.1.M1]
	at reactor.pool.PoolBuilder.build(PoolBuilder.java:296) ~[reactor-pool-0.0.1.M1.jar!/:0.0.1.M1]
	at io.r2dbc.pool.ConnectionPool.createConnectionPool(ConnectionPool.java:118) ~[r2dbc-pool-0.8.0.M8.jar!/:na]
```

Could you guys provide me with any idea to handle this nicely ?

**Comment by mp911de** [comment]
Thanks for report. I upgraded to a newer Reactor Pool version with #32 (`reactor-pool` 0.1.0.RC1). Can you upgrade and check whether the version upgrade addresses your issue?

If not, that's an issue for [reactor-pool](https://github.com/reactor/reactor-pool/issues).

**Comment by cambierr** [comment]
confirmed to be fixed with that version of reactor-pool !
