### ISSUE TITLE
Add warning log if ConnectionPool gets created with a nested ConnectionPool

### ISSUE THREAD

**Issue by leroyguillaume** [r2dbc/r2dbc-pool#40]
I've got a problem with the method `dispose()`. I'm newbie with R2DBC, Kotlin coroutines and reactive in general and it's probably a stupid error but I don't see it... Can you help?

```kotlin
class PoolTest {
    lateinit var dbConnectionPool: ConnectionPool
    lateinit var dbClient: R2dbc

    @BeforeEach
    fun beforeEach() {
        val dbConnectionFactory = ConnectionFactories.get(
            ConnectionFactoryOptions
                .builder()
                .option(Option.valueOf("driver"), "pool")
                .option(Option.valueOf("protocol"), "postgresql")
                .option(Option.valueOf("host"), "localhost")
                .option(Option.valueOf("port"), 5432)
                .option(Option.valueOf("database"), "xxx")
                .option(Option.valueOf("user"), "xxx")
                .option(Option.valueOf("password"), "xxx")
                .build()
        )
        dbConnectionPool = ConnectionPool(
            ConnectionPoolConfiguration
                .builder(dbConnectionFactory)
                .maxSize(10)
                .build()
        )
        dbClient = R2dbc(dbConnectionPool)
    }

    @AfterEach
    fun afterEach() {
        dbConnectionPool.dispose()
    }

    @Test
    fun test1() = runBlocking {
        val result = dbClient
            .withHandle { it.select("SELECT 1").mapRow { row, _ -> row[0] as Int } }
            .awaitFirst()
        println(result)
    }

    @Test
    fun test2() = runBlocking {
        val result = dbClient
            .withHandle { it.select("SELECT 2").mapRow { row, _ -> row[0] as Int } }
            .awaitFirst()
        println(result)
    }

    @Test
    fun test3() = runBlocking {
        val result = dbClient
            .withHandle { it.select("SELECT 3").mapRow { row, _ -> row[0] as Int } }
            .awaitFirst()
        println(result)
    }

    @Test
    fun test4() = runBlocking {
        val result = dbClient
            .withHandle { it.select("SELECT 4").mapRow { row, _ -> row[0] as Int } }
            .awaitFirst()
        println(result)
    }

    @Test
    fun test5() = runBlocking {
        val result = dbClient
            .withHandle { it.select("SELECT 5").mapRow { row, _ -> row[0] as Int } }
            .awaitFirst()
        println(result)
    }

    @Test
    fun test6() = runBlocking {
        val result = dbClient
            .withHandle { it.select("SELECT 6").mapRow { row, _ -> row[0] as Int } }
            .awaitFirst()
        println(result)
    }

    @Test
    fun test7() = runBlocking {
        val result = dbClient
            .withHandle { it.select("SELECT 7").mapRow { row, _ -> row[0] as Int } }
            .awaitFirst()
        println(result)
    }

    @Test
    fun test8() = runBlocking {
        val result = dbClient
            .withHandle { it.select("SELECT 8").mapRow { row, _ -> row[0] as Int } }
            .awaitFirst()
        println(result)
    }

    @Test
    fun test9() = runBlocking {
        val result = dbClient
            .withHandle { it.select("SELECT 9").mapRow { row, _ -> row[0] as Int } }
            .awaitFirst()
        println(result)
    }

    @Test
    fun test10() = runBlocking {
        val result = dbClient
            .withHandle { it.select("SELECT 10").mapRow { row, _ -> row[0] as Int } }
            .awaitFirst()
        println(result)
    }

    @Test
    fun test11() = runBlocking {
        val result = dbClient
            .withHandle { it.select("SELECT 11").mapRow { row, _ -> row[0] as Int } }
            .awaitFirst()
        println(result)
    }
}
```

The firsts 10 tests are OK. But the 11th test fails with error:
```
sorry, too many clients already
io.r2dbc.postgresql.ExceptionFactory$PostgresqlNonTransientResourceException: [53300] sorry, too many clients already
	at io.r2dbc.postgresql.ExceptionFactory.createException(ExceptionFactory.java:98)
	at io.r2dbc.postgresql.ExceptionFactory.handleErrorResponse(ExceptionFactory.java:110)
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:96)
	at reactor.core.publisher.FluxHandle$HandleConditionalSubscriber.onNext(FluxHandle.java:319)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onNext(MonoFlatMapMany.java:242)
	at reactor.core.publisher.FluxWindowPredicate$WindowFlux.drainRegular(FluxWindowPredicate.java:650)
	at reactor.core.publisher.FluxWindowPredicate$WindowFlux.drain(FluxWindowPredicate.java:728)
	at reactor.core.publisher.FluxWindowPredicate$WindowFlux.onNext(FluxWindowPredicate.java:770)
	at reactor.core.publisher.FluxWindowPredicate$WindowPredicateMain.onNext(FluxWindowPredicate.java:249)
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:112)
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:213)
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:213)
	at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:206)
	at reactor.netty.channel.FluxReceive.onInboundNext(FluxReceive.java:329)
	at reactor.netty.channel.ChannelOperations.onInboundNext(ChannelOperations.java:348)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:91)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:328)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:302)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1421)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:794)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:424)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:326)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

If I execute with psql the command `\watch SELECT query FROM pg_stat_activity WHERE query != '';` in parallel of tests execution, I can see number of opened connections increase by 10 at each test. I test to add a `Thread.sleep(5000)` after the `dbConnectionPool.dispose()` but no change.

Versions:
- PostgreSQL 11.1.1 (in docker container)
- Kotlin 1.3.50
- Kotlin Coroutines 1.3.2
- R2DBC 0.8.0.RC1

Thanks!

**Comment by mp911de** [comment]
You're applying double-pooling. 

By using `option(Option.valueOf("driver"), "pool")`, you're activating `r2dbc-pool` (transparent connection-pooling). The, you're wrapping that pool with another `ConnectionPool`. After closing the `ConnectionPool`, the second pool remains active and that's why you run out of connections.

You can fix the issue by changing:

```
.option(Option.valueOf("driver"), "pool")
.option(Option.valueOf("protocol"), "postgresql")
```

to 

```
.option(Option.valueOf("driver"), "postgresql")
```

It would probably make sense to log out a warning when `ConnectionPool` receives another `ConnectionPool` as `ConnectionFactory` to make folks aware that they are putting a pool in a pool.

**Comment by leroyguillaume** [comment]
Thank you, it's work!

And thanks for this amazing project!

**Comment by mp911de** [comment]
Let's keep this one open until we've added the warning log.
