### ISSUE TITLE
Make initial pool size configurable

### ISSUE THREAD

**Issue by brushmate** [r2dbc/r2dbc-pool#44]
When I try to create a new connection pool which should hold at most 5 connections I get an exception because the default initial size is 10.

This is an example that triggers the error:

    final ConnectionFactoryOptions options = ConnectionFactoryOptions.builder()
            .option(DRIVER, "pool")
            .option(PROTOCOL, "postgresql")
            .option(HOST, "host")
            .option(DATABASE, "database")
            .option(USER, "user")
            .option(PASSWORD, "password")
            .option(Option.valueOf("maxSize"), 5)
            .build();

    ConnectionFactories.get(options);

And this is the stacktrace:

    Exception in thread "main" java.lang.IllegalArgumentException: min must be less than or equal to max
    	at reactor.pool.AllocationStrategies$SizeBasedAllocationStrategy.<init>(AllocationStrategies.java:83)
    	at reactor.pool.PoolBuilder.sizeBetween(PoolBuilder.java:270)
    	at io.r2dbc.pool.ConnectionPool.createConnectionPool(ConnectionPool.java:139)
    	at io.r2dbc.pool.ConnectionPool.<init>(ConnectionPool.java:75)
    	at io.r2dbc.pool.PoolingConnectionFactoryProvider.create(PoolingConnectionFactoryProvider.java:74)
    	at io.r2dbc.pool.PoolingConnectionFactoryProvider.create(PoolingConnectionFactoryProvider.java:37)
    	at io.r2dbc.spi.ConnectionFactories.find(ConnectionFactories.java:44)
    	at io.r2dbc.spi.ConnectionFactories.get(ConnectionFactories.java:74)

From what I have seen it is not possible to configure the initial size using the `ConnectionFactoryOptions` but only using the `ConnectionPoolConfiguration.Builder`. Is there any reason why it should not be configurable via `ConnectionFactoryOptions`? Independently of this question: Shouldn't the initial size be tied to the maximum size? For example something like `initialSize = maxSize < 10 ? maxSize : 10`.

**Comment by mp911de** [comment]
Until now, no one asked and that is why we do not expose `initialSize` as configuration option. We should add that property.

There are some arrangements (just configuring `initialSize` or just configuring `maxSize`) in which values exceed the other boundary and we should address these in some way. That is:

* decrease the initial size if only max size is configured and its value is less than initial size
* increase the max size if only the initial size is configured and it exceeds the max size
