### ISSUE TITLE
max idle time and max lifetime have confusing semantics

### ISSUE THREAD

**Issue by osi** [r2dbc/r2dbc-pool#88]
in JDBC-based connection pools such as [Hikari](https://github.com/brettwooldridge/HikariCP) or [Tomcat](https://tomcat.apache.org/tomcat-7.0-doc/jdbc-pool.html), idle time applies to connection that are _not in use_ and the max lifetime is checked for connections after they have been returned to the pool.

r2dbc-pool defaults max idle time to 30 minutes. this means that any applications that use connections for long periods of time (such as using the `LISTEN` feature in PostgreSQL) will have their _in use_ connections unexpectedly terminated.

ideally, the two times would act similar to JDBC-based pools, limiting confusing for users with JDBC experience. alternatively, consider changing the names of the options to clearly indicate that they apply to in use connections.

(I do realize that the concepts here build upon reactor-pool's notion of idle and life times; I think there's an argument for enhancing reactor-pool to report on in-use vs idle discretely so it's consumers can have differing behavior)

**Comment by mp911de** [comment]
Thanks for raising this issue. It makes sense to align with JDBC pools regarding semantics.

**Comment by mp911de** [comment]
> r2dbc-pool defaults max idle time to 30 minutes. this means that any applications that use connections for long periods of time (such as using the LISTEN feature in PostgreSQL) will have their in use connections unexpectedly terminated.

That shouldn't be the case since a connection using the `LISTEN` feature is expected to be acquired and therefore it's not idle.

How would you use `LISTEN` with Postgres? Would you acquire all connections, issue a `LISTEN` statement and put the connection back to the pool expecting it remains subscribed?

FWIW, I added a test that verifies that the idle timeout does not apply to connections that are acquired.

**Comment by osi** [comment]
Thanks for the reply. I'm thinking that I have a bug where i'm incorrectly closing a connection that's in use (trying to figure out _where_ though). I'm using the new debug logging to help diagnose; it'd be useful it it said _which_ connection was acquired and released so I could match the pairs up.

**Comment by osi** [comment]
digging into this more, i've added logging to show that i'm getting the same underlying connection out of the pool twice. (meaning that it is in the pool multiple times). my gut is that there's a bug on the return-to-pool path that's adding it multiple times, as i'm also seeing 
```
java.lang.IllegalArgumentException: Too many permits returned: returned=1, would bring to 11/10
  at reactor.pool.AllocationStrategies$SizeBasedAllocationStrategy.returnPermits(AllocationStrategies.java:141)
  at reactor.pool.AbstractPool.destroyPoolable(AbstractPool.java:147)
  at reactor.pool.SimpleDequePool.drainLoop(SimpleDequePool.java:310)
  at reactor.pool.SimpleDequePool.drain(SimpleDequePool.java:204)
  at reactor.pool.SimpleDequePool.doAcquire(SimpleDequePool.java:199)
  at reactor.pool.AbstractPool$Borrower.request(AbstractPool.java:378)
  at reactor.core.publisher.FluxPeek$PeekSubscriber.request(FluxPeek.java:130)
```

I'm using `Arabba-SR7` (upgraded from SR6 today). Unfortunately I can't reproduce in isolation. 

My logging that backs this theory is
```
2020-10-01 22:23:03.844 DEBUG 852 --- [tor-tcp-epoll-1] c.n.b.e.p.LoggingConnectionFactory       : created CloseLoggingConnection{name='query/reader (over pool) 41', delegate=PooledConnection[CloseLoggingConnection{name='query/reader (under pool) 4', delegate=PostgresqlConnection{client=io.r2dbc.postgresql.client.ReactorNettyClient@261617c5, codecs=io.r2dbc.postgresql.codec.DefaultCodecs@4cb7990f}}]}
2020-10-01 22:23:03.851 DEBUG 852 --- [tor-tcp-epoll-1] c.n.b.e.p.LoggingConnectionFactory       : closed CloseLoggingConnection{name='query/reader (over pool) 41', delegate=PooledConnection[CloseLoggingConnection{name='query/reader (under pool) 4', delegate=PostgresqlConnection{client=io.r2dbc.postgresql.client.ReactorNettyClient@261617c5, codecs=io.r2dbc.postgresql.codec.DefaultCodecs@4cb7990f}}]} (onComplete)
2020-10-01 22:23:17.116 DEBUG 852 --- [tor-tcp-epoll-1] c.n.b.e.p.LoggingConnectionFactory       : created CloseLoggingConnection{name='query/reader (over pool) 51', delegate=PooledConnection[CloseLoggingConnection{name='query/reader (under pool) 4', delegate=PostgresqlConnection{client=io.r2dbc.postgresql.client.ReactorNettyClient@261617c5, codecs=io.r2dbc.postgresql.codec.DefaultCodecs@4cb7990f}}]}
2020-10-01 22:23:17.166 DEBUG 852 --- [tor-tcp-epoll-1] c.n.b.e.p.LoggingConnectionFactory       : closed CloseLoggingConnection{name='query/reader (over pool) 51', delegate=PooledConnection[CloseLoggingConnection{name='query/reader (under pool) 4', delegate=PostgresqlConnection{client=io.r2dbc.postgresql.client.ReactorNettyClient@261617c5, codecs=io.r2dbc.postgresql.codec.DefaultCodecs@4cb7990f}}]} (onComplete)
2020-10-01 22:23:17.179 DEBUG 852 --- [tor-tcp-epoll-1] c.n.b.e.p.LoggingConnectionFactory       : created CloseLoggingConnection{name='query/reader (over pool) 62', delegate=PooledConnection[CloseLoggingConnection{name='query/reader (under pool) 4', delegate=PostgresqlConnection{client=io.r2dbc.postgresql.client.ReactorNettyClient@261617c5, codecs=io.r2dbc.postgresql.codec.DefaultCodecs@4cb7990f}}]}
2020-10-01 22:23:17.225 DEBUG 852 --- [tor-tcp-epoll-1] c.n.b.e.p.LoggingConnectionFactory       : created CloseLoggingConnection{name='query/reader (over pool) 70', delegate=PooledConnection[CloseLoggingConnection{name='query/reader (under pool) 4', delegate=PostgresqlConnection{client=io.r2dbc.postgresql.client.ReactorNettyClient@261617c5, codecs=io.r2dbc.postgresql.codec.DefaultCodecs@4cb7990f}}]}
2020-10-01 22:23:19.297 DEBUG 852 --- [tor-tcp-epoll-1] c.n.b.e.p.LoggingConnectionFactory       : closed CloseLoggingConnection{name='query/reader (over pool) 62', delegate=PooledConnection[CloseLoggingConnection{name='query/reader (under pool) 4', delegate=PostgresqlConnection{client=io.r2dbc.postgresql.client.ReactorNettyClient@261617c5, codecs=io.r2dbc.postgresql.codec.DefaultCodecs@4cb7990f}}]} (onComplete)
2020-10-01 22:23:19.302 DEBUG 852 --- [tor-tcp-epoll-1] c.n.b.e.p.LoggingConnectionFactory       : closed CloseLoggingConnection{name='query/reader (over pool) 70', delegate=PooledConnection[CloseLoggingConnection{name='query/reader (under pool) 4', delegate=PostgresqlConnection{client=io.r2dbc.postgresql.client.ReactorNettyClient@261617c5, codecs=io.r2dbc.postgresql.codec.DefaultCodecs@4cb7990f}}]} (onComplete)
```

the same under-pool connection gets returned twice as 62 and 70. this explains what i saw when i opened this ticket; if a connection was in the pool twice, but in the state where one was in-use and the other was not, the idle timeout would end up closing the connection in-use.

**Comment by osi** [comment]
I'm closing this in favor of #92 which represents an actual observed problem. This was a signal I misinterpreted.
